channels:
  - conda-forge
  - anaconda
dependencies:
  - python==3.11
  - pytorch==2.0
  - numpy==1.25
  - tqdm==4.66
  - scikit-learn=1.3
  - keras==3.0.2
  - ipykernel
  - pydot
  - opencv
  - pillow
